# .travis.yml

language: node_js
node_js:
  - "lts/*"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Shanghai'
install:
- yarn
script:
  - yarn docs:build
deploy:
  provider: pages
  cleanup: true
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  verbose: true
  on:
    branch: master
